//Parse 

module.exports = {
	parseCountry: function(country){
		var parsed=removeStopWords(removeDiacritics(country.trim().toLowerCase()));
		switch(parsed){
			case "peru":
				return "Perú";
			default:
				return false;
		}
	},
	parseDate: function(country){
		return false;
	},
    countryListEN: [
        'Afghanistan',
        'Albania (Republic of)',
        'Algeria (People\'s Democratic Republic of)',
        'Andorra (Principality of)',
        'Angola (Republic of)',
        'Anguilla',
        'Antigua and Barbuda',
        'Argentine Republic',
        'Armenia (Republic of)',
        'Aruba',
        'Australia',
        'Austria',
        'Azerbaijani Republic',
        'Bahamas (Commonwealth of the)',
        'Bahrain (Kingdom of)',
        'Bangladesh (People\'s Republic of)',
        'Barbados',
        'Belarus (Republic of)',
        'Belgium',
        'Belize',
        'Benin (Republic of)',
        'Bermuda',
        'Bolivia (Republic of)',
        'Bosnia and Herzegovina',
        'Botswana (Republic of)',
        'Brazil (Federative Republic of)',
        'British Virgin Islands',
        'Brunei Darussalam',
        'Bulgaria (Republic of)',
        'Burkina Faso',
        'Burundi (Republic of)',
        'Cambodia (Kingdom of)',
        'Cameroon (Republic of)',
        'Canada',
        'Cape Verde (Republic of)',
        'Cayman Islands',
        'Central African Republic',
        'Chad (Republic of)',
        'Chile',
        'China (People\'s Republic of)',
        'Colombia (Republic of)',
        'Congo (Republic of the)',
        'Cook Islands',
        'Costa Rica',
        'Cote d\'Ivoire (Republic of)',
        'Croatia (Republic of)',
        'Cuba',
        'Cyprus (Republic of)',
        'Czech Republic',
        'Democratic Republic of the Congo',
        'Denmark',
        'Djibouti (Republic of)',
        'Dominica (Commonwealth of)',
        'Dominican Republic',
        'Ecuador',
        'Egypt (Arab Republic of)',
        'El Salvador (Republic of)',
        'EMPTY',
        'Equatorial Guinea (Republic of)',
        'Estonia (Republic of)',
        'Ethiopia (Federal Democratic Republic of)',
        'Faroe Islands',
        'Fiji (Republic of)',
        'Finland',
        'France',
        'French Polynesia (Territoire francais d\'outre-mer)',
        'Gabonese Republic',
        'Gambia (Republic of the)',
        'Georgia',
        'Germany (Federal Republic of)',
        'Ghana',
        'Gibraltar',
        'Greece',
        'Greenland (Denmark)',
        'Grenada',
        'Guadeloupe (French Department of)',
        'Guam',
        'Guatemala (Republic of)',
        'Guinea-Bissau (Republic of)',
        'Guinea (Republic of)',
        'Guyana',
        'Haiti (Republic of)',
        'Honduras (Republic of)',
        'Hongkong, China',
        'Hungary (Republic of)',
        'Iceland',
        'India (Republic of)',
        'Indonesia (Republic of)',
        'Iran (Islamic Republic of)',
        'Iraq (Republic of)',
        'Ireland',
        'Isle of Man',
        'Israel (State of)',
        'Italy',
        'Jamaica',
        'Japan',
        'Jersey',
        'Jordan (Hashemite Kingdom of)',
        'Kazakhstan (Republic of)',
        'Kenya (Republic of)',
        'Korea (Republic of)',
        'Kuwait (State of)',
        'Kyrgyz Republic',
        'Lao People\'s Democratic Republic',
        'Latvia (Republic of)',
        'Lebanon',
        'Lesotho (Kingdom of)',
        'Liberia (Republic of)',
        'Libya (Socialist People\'s Libyan Arab Jamahiriya)',
        'Liechtenstein (Principality of)',
        'Lithuania (Republic of)',
        'Luxembourg',
        'Macao, China',
        'Macedonia (The Former Yugoslav Republic of)',
        'Madagascar (Republic of)',
        'Malawi',
        'Malaysia',
        'Maldives (Republic of)',
        'Mali (Republic of)',
        'Malta',
        'Martinique (French Department of)',
        'Mauritania (Islamic Republic of)',
        'Mauritius (Republic of)',
        'Mexico',
        'Moldova (Republic of)',
        'Monaco (Principality of)',
        'Mongolia',
        'Montenegro (Republic of)',
        'Montserrat',
        'Morocco (Kingdom of)',
        'Mozambique (Republic of)',
        'Myanmar (Union of)',
        'Namibia (Republic of)',
        'Nepal',
        'Netherlands Antilles',
        'Netherlands (Kingdom of the)',
        'New Caledonia (Territoire francais d\'outre-mer)',
        'New Zealand',
        'Nicaragua',
        'Nigeria (Federal Republic of)',
        'Niger (Republic of the)',
        'Non Terrestrial (NT)',
        'Norway',
        'Oman (Sultanate of)',
        'Pakistan (Islamic Republic of)',
        'Palestine',
        'Panama (Republic of)',
        'Papua New Guinea',
        'Paraguay (Republic of)',
        'Peru',
        'Philippines (Republic of the)',
        'Poland (Republic of)',
        'Portugal',
        'Puerto Rico',
        'Qatar (State of)',
        'Reunion (French Department of)',
        'Romania',
        'Russian Federation',
        'Rwandese Republic',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Samoa (Independent State of)',
        'Sao Tome and Principe (Democratic Republic of)',
        'Saudi Arabia (Kingdom of)',
        'Senegal (Republic of)',
        'Serbia (Republic of)',
        'Seychelles (Republic of)',
        'Sierra Leone',
        'Singapore (Republic of)',
        'Slovak Republic',
        'Slovenia (Republic of)',
        'South Africa (Republic of)',
        'Spain',
        'Sri Lanka (Democratic Socialist Republic of)',
        'Sudan (Republic of the)',
        'Suriname (Republic of)',
        'Sweden',
        'Switzerland (Confederation of)',
        'Syrian Arab Republic',
        'Taiwan',
        'Tajikistan (Republic of)',
        'Tanzania (United Republic of)',
        'Thailand',
        'Timor-Leste (Democratique Republic of)',
        'Togolese Republic',
        'Tonga (Kingdom of)',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Turks and Caicos Islands',
        'Uganda (Republic of)',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom of Great Britain and Northern Ireland, UK',
        'United States of America, USA',
        'United States Virgin Islands',
        'UNKNOWN',
        'Uruguay (Eastern Republic of)',
        'Uzbekistan (Republic of)',
        'Vanuatu (Republic of)',
        'Venezuela (Bolivarian Republic of)',
        'Vietnam (Socialist Republic of)',
        'Yemen (Republic of)',
        'Zambia (Republic of)',
        'Zimbabwe (Republic of)'
      ],
      countryListES: [
        'Afganistán',
        'Albania',
        'Argelia',
        'Andorra',
        'Angola',
        'Anguila',
        'Antigua y Barbuda',
        'Argentina',
        'Armenia',
        'Aruba',
        'Australia',
        'Austria',
        'Azerbaiyán',
        'Bahamas',
        'Baréin',
        'Bangladés',
        'Barbados',
        'Bielorrusia',
        'Bélgica',
        'Belice',
        'Benín',
        'Bermudas',
        'Bolivia',
        'Bosnia y Herzegovina',
        'Botsuana',
        'Brasil',
        'Islas Vírgenes Británicas',
        'Brunéi',
        'Bulgaria',
        'Burkina Faso',
        'Burundi',
        'Camboya',
        'Camerún',
        'Canadá',
        'Cabo Verde',
        'Islas Caimán',
        'República Centroafricana',
        'Chad',
        'Chile',
        'China',
        'Colombia',
        'República del Congo',
        'Islas Cook',
        'Costa Rica',
        'Costa de Marfíl',
        'Croacia',
        'Cuba',
        'Chipre',
        'República Checa',
        'República Democrática del Congo',
        'Dinamarca',
        'Yibuti',
        'Dominica',
        'República Dominicana',
        'Ecuador',
        'Egipto',
        'El salvador',
        'Vacío',
        'Guinea ecuatorial',
        'Estonia',
        'Etiopía',
        'Islas Feroe',
        'Fiyi',
        'Finlandia',
        'Francia',
        'Polinesia Francesa',
        'Gabón',
        'Gambia',
        'Georgia',
        'Alemania',
        'Ghana',
        'Gibraltar',
        'Grecia',
        'Dinamarca',
        'Granada',
        'Guadalupe',
        'Guam',
        'Guatemala',
        'Guinea-Bisáu',
        'Guinea',
        'Guyana',
        'Haití',
        'Honduras',
        'Hong Kong, China',
        'Hungría',
        'Islandia',
        'India',
        'Indonesia',
        'Irán',
        'Irak',
        'Irlanda',
        'Isla de man',
        'Israel',
        'Italia',
        'Jamaica',
        'Japón',
        'Jersey',
        'Jordania',
        'Kazajistán',
        'Kenia',
        'Corea',
        'Kuwait',
        'Kirguistán',
        'Laos',
        'Letonia',
        'Líbano',
        'Lesoto',
        'Liberia',
        'Libia',
        'Liechtenstein',
        'Lituania',
        'Luxemburgo',
        'Macao',
        'Macedonia',
        'Madagascar',
        'Malaui',
        'Malasia',
        'Maldivas',
        'Malí',
        'Malta',
        'Martinica',
        'Mauritania',
        'Mauricio',
        'México',
        'Moldavia',
        'Mónaco',
        'Mongolia',
        'Montenegro',
        'Montserrat',
        'Marruecos',
        'Mozambique',
        'Birmania',
        'Namibia',
        'Nepal',
        'Antillas Neerlandesas',
        'Países Bajos',
        'Calcedonia',
        'Nueva Zelanda',
        'Nicaragua',
        'Nigeria',
        'Níger',
        'No terrestre, satélite',
        'Noruega',
        'Omán',
        'Pakistán',
        'Palestina',
        'Panamá',
        'Papúa Nueva Guinea',
        'Paraguay',
        'Perú',
        'Filipinas',
        'Polonia',
        'Portugal',
        'Puerto Rico',
        'Catar',
        'Reunión',
        'Rumanía',
        'Rusia',
        'Ruanda',
        'San Cristóbal y Nieves',
        'Santa Lucía',
        'San Vicente y las Granadinas',
        'Samoa',
        'Santo Tomé y Príncipe',
        'Arabia Saudita',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leona',
        'Singapur',
        'Eslovaquia',
        'Eslovenia',
        'Sudáfrica',
        'España',
        'Sri Lanka',
        'Sudán',
        'Surinam',
        'Suecia',
        'Suiza',
        'Siria',
        'Taiwán',
        'Tayikistán',
        'Tanzania',
        'Tailandia',
        'Timor Oriental',
        'Togo',
        'Tonga',
        'Trinidad y Tobago',
        'Túnez',
        'Turquía',
        'Turkmenistán',
        'Islas Turcas y Caicos',
        'Uganda',
        'Ucrania',
        'Emiratos Árabes Unidos',
        'Reino Unido',
        'Estados Unidos, EEUU',
        'Islas Vírgenes de los Estados Unidos',
        'Desconocido',
        'Uruguay',
        'Uzbekistán',
        'Vanuatu',
        'Venezuela',
        'Vietnam',
        'Yemen',
        'Zambia',
        'Zimbabue',
      ],
      subscribersGeneral: [
        'A1 TELEKOM',
        'ACELL-MOOV',
        'AFRICELL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL',
        'AIRCEL DIGILINK',
        'AIRCEL DIGILINK',
        'AIRCEL DIGILINK',
        'AIRTEL',
        'AIRTEL RUANDA',
        'AL MADAR MOBILES',
        'ALFA',
        'ALTYN ASYR MC',
        'AM CLARO',
        'AMAZONIA CELULAR',
        'AMC MOBIL',
        'AMT FINLANDIA',
        'ANTEL',
        'APUA',
        'AREEBA',
        'ARMENTEL',
        'ASIACELL',
        'ASTELIT',
        'AT&T MOBILITY',
        'ATLANTIQUE TELECOM',
        'ATM MOBILIS',
        'AVEA ',
        'AWCC',
        'AWN',
        'AZERCELL',
        'AZERFON',
        'B-MOBILE BRUNEI',
        'BABILON-MOBILE',
        'BAKCELL',
        'BASE',
        'BATELCO',
        'BCTI',
        'BELIZE TELECOM LIMITED - DIGICELL',
        'BELL MOBILITY',
        'BEMOBILE LIMITED',
        'BEST',
        'BH TELECOM',
        'BHARAT SANCHAR NIGAM',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BHARTI AIRTEL',
        'BITE',
        'BITE ',
        'BMOBILE',
        'BOUYGUES TELECOM',
        'BRASIL TELECOM GSM',
        'BTC',
        'BTC MOBILE',
        'BTC-VIVACOM',
        'C&W GUERNSEY LIMITED',
        'CABLE & WIRELESS',
        'CABLE & WIRELESS MOVIL',
        'CADCOMMS',
        'CCT',
        'CELCOM',
        'CELL C',
        'CELLCOM',
        'CELLCOM GUINEA',
        'CELLPLUS ORANGE',
        'CELTEL',
        'CENTENNIAL CELLULAR',
        'CENTERTEL',
        'CHINA MOBILE',
        'CHINA UNICOM',
        'CHINGUITEL',
        'CHUNGHWA TELECOM',
        'CLARO',
        'CNT',
        'COM4',
        'COMCEL',
        'COMCEL ',
        'COMCEL - TIGO',
        'COMIUM',
        'COMVIQ - TELE2',
        'CONECEL',
        'COSCOM ',
        'COSMOTE',
        'CROATIAN TELECOM T-MOBILE',
        'CSL LTD',
        'CSTMOVEL',
        'CTBC',
        'CTE TELECOM PERSONAL',
        'CTM',
        'CUBACEL',
        'CVMOVEL',
        'CYTA',
        'DAUPHIN AMIGO',
        'DHIMOBILE',
        'DIALOG GSM - DIALOG SAT',
        'DIGI',
        'DIGICEL',
        'DIGICEL ',
        'DIGICEL  PNG',
        'DIGICEL ANTILLES FRANCAISES',
        'DIGICEL CURACAO',
        'DIGICEL SURINAME',
        'DIGITAL COMM',
        'DIGITEL',
        'DJIBOUTI',
        'DNA FINLAND',
        'DOCOMO',
        'DSTCOM',
        'DTAC - TAC Total Access Com',
        'DTAC - Trinet',
        'EMPTY',
        'E-PLUS',
        'EACCESS EMOBILE',
        'EAGLE MOBILE',
        'ECONET',
        'ECONET EZI-CEL',
        'EITC - DU',
        'EKATERIMBURG MOTIV',
        'ELISA',
        'EMT',
        'EMTEL',
        'ENITEL CLARO',
        'ENTEL PCS',
        'ERONET',
        'ESSAR TELECOM',
        'ETHIO TELECOM - ETH MTN',
        'ETISALAT',
        'ETISALAT - ATLANTIQUE TELECOM TELECEL',
        'ETISALAT BENIN',
        'ETISALAT MISR',
        'ETISALAT TIGO',
        'EXPRESSO',
        'FAR EASTONE',
        'FAROESE TELECOM',
        'FE VELCOM',
        'FREE MOBILE',
        'GAMCEL',
        'GCI COMMUNICATIONS',
        'GEOCELL',
        'GIBTELECOM',
        'GLOBALIVE WIND',
        'GLOBALSTAR',
        'GLOBALSTAR - TESAM',
        'GLOBE TELECOM',
        'GLOBUL',
        'GLOMOBILE',
        'GO MOBILE',
        'GRAMEENPHONE',
        'GTEL MOBILE',
        'H3G',
        'H3G AUSTRIA',
        'HI3G',
        'HI3G 3 DK',
        'HITS',
        'HKT PCCW',
        'HOT MOBILE',
        'HUTCHISON',
        'ICE',
        'IDEA',
        'IDEA',
        'IDEA',
        'IDEA',
        'IDEA',
        'IDEA',
        'IDEA',
        'IDEA',
        'IDEA',
        'IDEA',
        'IDEA',
        'IDEA',
        'IDEA',
        'IMC VIKING WIRELESS',
        'IMMIX WIRELESS',
        'INDIGO SOMONCOM',
        'INDIGO TAJIKISTAN',
        'INDOSAT',
        'INTERCEL',
        'IUSACELL',
        'JASPER',
        'JASPER WIRELESS',
        'JAWWAL',
        'JAZZ TELECOM',
        'JERSEY TELECOMS',
        'JORDAN MOBILE ZAIN',
        'K-MOBILE BEELINE',
        'K\'CELL',
        'KDDI',
        'KG TELECOM',
        'KOKANET',
        'KOREK',
        'KPN',
        'KT',
        'KTC VIVA',
        'KYIVSTAR',
        'LAO TELECOMMUNICATIONS - LTC',
        'LATELZ',
        'LG UPLUS',
        'LIBERCOM',
        'LIBERTIS',
        'LIFFEY TELECOM',
        'LIME',
        'LIPPO',
        'LMT',
        'LONESTAR CELL',
        'LOOP MOBILE',
        'LYCAMOBILE',
        'MAGTICOM',
        'MAINGATE',
        'MALITEL',
        'MANX TELECOM',
        'MARI ',
        'MAROC TELECOM - IAM ',
        'MASCOM',
        'MATTEL SA',
        'MAXIS',
        'MCEL',
        'MCI',
        'MEDITEL',
        'MEGACOM',
        'MEGAFON',
        'MELITA MOBILE',
        'METEOR',
        'METFONE',
        'MIC TIGO',
        'MILLICOM',
        'MOBICOM',
        'MOBIFONE',
        'MOBILAND',
        'MOBILEONE',
        'MOBILINK',
        'MOBILTEL',
        'MOBILY',
        'MOBINIL',
        'MOBISTAR',
        'MOBITEL',
        'MOBITEL - M SAT',
        'MOBITEL - MEGACOM',
        'MOLDCELL',
        'MONACO TELECOM',
        'MOVICEL',
        'MOVIL DE ENTEL',
        'MOVILNET',
        'MOVISTAR',
        'MOVISTAR SLOVAKIA',
        'MOVITEL',
        'MTC',
        'MTC TOUCH',
        'MTC VODAFONE BAHRAIN',
        'MTC-KUWAIT',
        'MTEL',
        'MTML MAURITIUS',
        'MTN',
        'MTN IRANCELL',
        'MTNL',
        'MTNL',
        'MTS',
        'MTX',
        'NATCOM',
        'NAWRAS',
        'NCC',
        'NEO',
        'NEPAL TELECOM MOBILE',
        'NETWORK NORWAY',
        'NEXTEL',
        'NOVA',
        'NRJ FRANCIA',
        'NUEVATEL',
        'NUR TELECOM',
        'O2',
        'OASIS',
        'OI',
        'OLA - TIGO',
        'OMAN MOBILE',
        'OMNITEL',
        'ONATEL',
        'ONE DOO SKOPJE ',
        'OOREDOO',
        'OOREDOO MYANMAR',
        'OPT - NC MOBILIS',
        'OPTIMUS',
        'OPTUS',
        'ORANGE',
        'ORANGE ',
        'ORANGE F',
        'ORANGE GQ',
        'ORANGE PTY LIMITED VISTA',
        'ORANGE REUNION',
        'ORASCOM',
        'OTT- ORASCOM TUNISIANA',
        'OUTREMER',
        'P&T LUXEMBUR',
        'P4',
        'PAKTEL',
        'PELEPHONE',
        'PERSONAL',
        'PLUS COMMUNICATION',
        'POLKOMTEL',
        'POLSAT',
        'POWERCOM LEO TM',
        'PRIMETEL',
        'PROXIMUS',
        'Q-TELECOM',
        'QATAR TELECOM',
        'QCELL',
        'RADIOMOBIL T-MOBILE',
        'RCS&RDS',
        'RELIANCE TELECOM LTD',
        'RITABELL - TELE2.MOBIIL',
        'ROBI AXIATA',
        'ROGERS WIRELESS',
        'ROSTELECOM',
        'RS - M:TEL MOBI\'S',
        'SABAFON ',
        'SAFARICOM',
        'SASKATCHEWAN TELECOMMUNICATIONS',
        'SAUDI TELECOM AL JAWAL',
        'SCANCOM',
        'SENTEL',
        'SETAR GSM',
        'SFR',
        'SI.MOBIL',
        'SIMINN',
        'SINGTEL SINGTEL-MOBILELINK',
        'SK TELECOM',
        'SKY MOBILE BEELINE ',
        'SMART',
        'SMARTONE',
        'SMARTS',
        'SOFTBANK MOBILE',
        'SONOFON',
        'SPACETEL',
        'SPACETEL BENIN',
        'SPICE NEPAL SNPL',
        'SPRINT PCS',
        'STARHUB',
        'SUDATEL',
        'SUNRISE',
        'SWISSCOM',
        'SYRIATEL',
        'T +',
        'T-MOBILE',
        'T-MOBILE NL',
        'T-MOBILE UK',
        'T2',
        'TACOM',
        'TAIWAN MOBILE',
        'TANGO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TATA DOCOMO',
        'TCC',
        'TDC MOBIL',
        'TDC NORWAY',
        'TDCA',
        'TELCEL',
        'TELCELL',
        'TELE GREENLAND',
        'TELE2',
        'TELE2 RUSIA',
        'TELECEL',
        'TELECOM',
        'TELECOM ',
        'TELECOMUNICATION',
        'TELEFONICA',
        'TELEFONICA DE NICARAGUA',
        'TELEFONICA GUATEMALA',
        'TELEFONICA MOVILES',
        'TELEFONICA PANAMA',
        'TELEKOM',
        'TELEKOM SL - MOBITEL',
        'TELEKOM SRBIJE',
        'TELEMOVIL - TIGO',
        'TELENOR',
        'TELENOR MYANMAR',
        'TELENOR PANNON',
        'TELESUR',
        'TELFORT',
        'TELIA',
        'TELIA DK',
        'TELIA SONERA',
        'TELIASONERA',
        'TELKOM',
        'TELKOMSEL',
        'TELMA MOBILE',
        'TELSTRA TELECOM',
        'TELUS',
        'THURAYA SATELLITE',
        'TIGO RUANDA',
        'TIM',
        'TIM',
        'TIM',
        'TIMOR TELECOM',
        'TMN',
        'TNM',
        'TOGOCEL',
        'TRILOGY',
        'TRIMOB',
        'TRUE MOVE - REAL FUTURE',
        'TUNTEL',
        'TURKCELL',
        'TUSMOBIL',
        'TWO DEGREES',
        'U-MOBILE',
        'UFONE',
        'UGANDA TELECOM MOBILE',
        'UMNIAH',
        'UNINOR',
        'UNINOR',
        'UNION TELEPHONE',
        'UNITEL',
        'UNKNOWN',
        'UTS',
        'VEGL VODAFONE',
        'VEL VODAFONE',
        'VERIZON WIRELESS',
        'VIAERO WIRELESS',
        'VIBO',
        'VIDEOTRON',
        'VIETNAMOBILE',
        'VIETTEL MOBILE',
        'VIMPELCOM',
        'VINAPHONE',
        'VINI',
        'VIP',
        'VIP OPERATOR',
        'VIPNET',
        'VIRGIN',
        'VITELCOM',
        'VIVA BAHRAIN',
        'VIVACELL',
        'VIVO',
        'VIVO BRATC',
        'VODACOM',
        'VODAFONE',
        'VOX',
        'VTR',
        'WANA',
        'WARID',
        'WATANIY',
        'WATANIYA',
        'WIND',
        'WIND HELLAS',
        'XFERA',
        'XL AXIATA',
        'YENISEYTELECOM',
        'ZAIN',
        'ZAIN ARABIA',
        'ZAIN IQ',
        'ZANTEL',
    ],
    subscribersConcrete: [
        'A1 TELEKOM',
        'ACELL-MOOV',
        'AFRICELL',
        'AIRCEL (ANDHRA PRADESH)',
        'AIRCEL (ASSAM)',
        'AIRCEL (BIHAR JHARKHAND)',
        'AIRCEL (CHENNAI)',
        'AIRCEL (DELHI)',
        'AIRCEL (GUJARAT)',
        'AIRCEL (HARYANA)',
        'AIRCEL (HIMACHAL PRADESH)',
        'AIRCEL (JAMU KASHMIR)',
        'AIRCEL (KARNATAKA)',
        'AIRCEL (KERALA)',
        'AIRCEL (KOLKATA)',
        'AIRCEL (MADHYA PRADESH)',
        'AIRCEL (MAHARASHTRA)',
        'AIRCEL (MUMBAI)',
        'AIRCEL (NORTH EAST)',
        'AIRCEL (ORISSA)',
        'AIRCEL (PUNJAB)',
        'AIRCEL (RAJASTHAN)',
        'AIRCEL (WEST BENGAL)',
        'AIRCEL DIGILINK (Haryana)',
        'AIRCEL DIGILINK (Rajasthan)',
        'AIRCEL DIGILINK (UP East)',
        'AIRTEL',
        'AIRTEL RUANDA',
        'AL MADAR MOBILES',
        'ALFA',
        'ALTYN ASYR MC',
        'AM CLARO',
        'AMAZONIA CELULAR',
        'AMC MOBIL',
        'AMT FINLANDIA',
        'ANTEL',
        'APUA',
        'AREEBA',
        'ARMENTEL',
        'ASIACELL',
        'ASTELIT',
        'AT&T MOBILITY',
        'ATLANTIQUE TELECOM',
        'ATM MOBILIS',
        'AVEA ',
        'AWCC',
        'AWN',
        'AZERCELL',
        'AZERFON',
        'B-MOBILE BRUNEI',
        'BABILON-MOBILE',
        'BAKCELL',
        'BASE',
        'BATELCO',
        'BCTI',
        'BELIZE TELECOM LIMITED - DIGICELL',
        'BELL MOBILITY',
        'BEMOBILE LIMITED',
        'BEST',
        'BH TELECOM',
        'BHARAT SANCHAR NIGAM',
        'BHARTI AIRTEL (Andhra Pradesh)',
        'BHARTI AIRTEL (Calcuta)',
        'BHARTI AIRTEL (Chennai)',
        'BHARTI AIRTEL (Gujarat)',
        'BHARTI AIRTEL (Haryana)',
        'BHARTI AIRTEL (Karnataka)',
        'BHARTI AIRTEL (Kerala)',
        'BHARTI AIRTEL (Madhya Pradesh)',
        'BHARTI AIRTEL (Maharashtra & Goa)',
        'BHARTI AIRTEL (Mumbai)',
        'BHARTI AIRTEL (Nueva Delhi)',
        'BHARTI AIRTEL (Punjab)',
        'BHARTI AIRTEL (Rajasthan)',
        'BHARTI AIRTEL (Tamil Nadu',
        'BHARTI AIRTEL (UP West)',
        'BITE',
        'BITE ',
        'BMOBILE',
        'BOUYGUES TELECOM',
        'BRASIL TELECOM GSM',
        'BTC',
        'BTC MOBILE',
        'BTC-VIVACOM',
        'C&W GUERNSEY LIMITED',
        'CABLE & WIRELESS',
        'CABLE & WIRELESS MOVIL',
        'CADCOMMS',
        'CCT',
        'CELCOM',
        'CELL C',
        'CELLCOM',
        'CELLCOM GUINEA',
        'CELLPLUS ORANGE',
        'CELTEL',
        'CENTENNIAL CELLULAR',
        'CENTERTEL',
        'CHINA MOBILE',
        'CHINA UNICOM',
        'CHINGUITEL',
        'CHUNGHWA TELECOM',
        'CLARO',
        'CNT',
        'COM4',
        'COMCEL',
        'COMCEL ',
        'COMCEL - TIGO',
        'COMIUM',
        'COMVIQ - TELE2',
        'CONECEL',
        'COSCOM ',
        'COSMOTE',
        'CROATIAN TELECOM T-MOBILE',
        'CSL LTD',
        'CSTMOVEL',
        'CTBC',
        'CTE TELECOM PERSONAL',
        'CTM',
        'CUBACEL',
        'CVMOVEL',
        'CYTA',
        'DAUPHIN AMIGO',
        'DHIMOBILE',
        'DIALOG GSM - DIALOG SAT',
        'DIGI',
        'DIGICEL',
        'DIGICEL ',
        'DIGICEL  PNG',
        'DIGICEL ANTILLES FRANCAISES (BOUYGUES TELECOM CARAIBE)',
        'DIGICEL CURACAO',
        'DIGICEL SURINAME',
        'DIGITAL COMM',
        'DIGITEL',
        'DJIBOUTI',
        'DNA FINLAND',
        'DOCOMO',
        'DSTCOM',
        'DTAC - TAC Total Access Com',
        'DTAC - Trinet',
        'EMPTY',
        'E-PLUS',
        'EACCESS EMOBILE',
        'EAGLE MOBILE',
        'ECONET',
        'ECONET EZI-CEL',
        'EITC - DU',
        'EKATERIMBURG MOTIV',
        'ELISA',
        'EMT',
        'EMTEL',
        'ENITEL CLARO',
        'ENTEL PCS',
        'ERONET',
        'ESSAR TELECOM (ECONET)',
        'ETHIO TELECOM - ETH MTN',
        'ETISALAT',
        'ETISALAT - ATLANTIQUE TELECOM TELECEL',
        'ETISALAT BENIN',
        'ETISALAT MISR',
        'ETISALAT TIGO',
        'EXPRESSO',
        'FAR EASTONE',
        'FAROESE TELECOM',
        'FE VELCOM',
        'FREE MOBILE',
        'GAMCEL',
        'GCI COMMUNICATIONS',
        'GEOCELL',
        'GIBTELECOM',
        'GLOBALIVE WIND',
        'GLOBALSTAR',
        'GLOBALSTAR - TESAM',
        'GLOBE TELECOM',
        'GLOBUL',
        'GLOMOBILE',
        'GO MOBILE',
        'GRAMEENPHONE',
        'GTEL MOBILE',
        'H3G',
        'H3G AUSTRIA',
        'HI3G',
        'HI3G 3 DK',
        'HITS',
        'HKT PCCW',
        'HOT MOBILE',
        'HUTCHISON',
        'ICE',
        'IDEA (ANDHRA PRADESH)',
        'IDEA (HIMACHAL PRADESH)',
        'IDEA (J & K)',
        'IDEA (KARNATAKA)',
        'IDEA (KERALA AGRA)',
        'IDEA (MAHARASTRA GOA)',
        'IDEA (NEW DELHI)',
        'IDEA (NORTH EAST)',
        'IDEA (ORISSA)',
        'IDEA (RAJASHTAN)',
        'IDEA (UP EAST)',
        'IDEA (UP WEST)',
        'IDEA (WEST BENGAL)',
        'IMC VIKING WIRELESS',
        'IMMIX WIRELESS',
        'INDIGO SOMONCOM',
        'INDIGO TAJIKISTAN',
        'INDOSAT',
        'INTERCEL',
        'IUSACELL',
        'JASPER',
        'JASPER WIRELESS',
        'JAWWAL',
        'JAZZ TELECOM',
        'JERSEY TELECOMS',
        'JORDAN MOBILE ZAIN',
        'K-MOBILE BEELINE',
        'K\'CELL',
        'KDDI',
        'KG TELECOM',
        'KOKANET',
        'KOREK',
        'KPN',
        'KT',
        'KTC VIVA',
        'KYIVSTAR',
        'LAO TELECOMMUNICATIONS - LTC',
        'LATELZ',
        'LG UPLUS',
        'LIBERCOM',
        'LIBERTIS',
        'LIFFEY TELECOM',
        'LIME',
        'LIPPO',
        'LMT',
        'LONESTAR CELL',
        'LOOP MOBILE (MUMBAI)',
        'LYCAMOBILE',
        'MAGTICOM',
        'MAINGATE',
        'MALITEL',
        'MANX TELECOM',
        'MARI ',
        'MAROC TELECOM - IAM ',
        'MASCOM',
        'MATTEL SA',
        'MAXIS',
        'MCEL',
        'MCI',
        'MEDITEL',
        'MEGACOM',
        'MEGAFON',
        'MELITA MOBILE',
        'METEOR',
        'METFONE',
        'MIC TIGO',
        'MILLICOM',
        'MOBICOM',
        'MOBIFONE',
        'MOBILAND',
        'MOBILEONE',
        'MOBILINK',
        'MOBILTEL',
        'MOBILY',
        'MOBINIL',
        'MOBISTAR',
        'MOBITEL',
        'MOBITEL - M SAT',
        'MOBITEL - MEGACOM',
        'MOLDCELL',
        'MONACO TELECOM',
        'MOVICEL',
        'MOVIL DE ENTEL',
        'MOVILNET',
        'MOVISTAR',
        'MOVISTAR SLOVAKIA',
        'MOVITEL',
        'MTC',
        'MTC TOUCH',
        'MTC VODAFONE BAHRAIN',
        'MTC-KUWAIT',
        'MTEL',
        'MTML MAURITIUS',
        'MTN',
        'MTN IRANCELL',
        'MTNL (Mumbai)',
        'MTNL (New Delhi)',
        'MTS',
        'MTX',
        'NATCOM',
        'NAWRAS',
        'NCC',
        'NEO',
        'NEPAL TELECOM MOBILE',
        'NETWORK NORWAY',
        'NEXTEL',
        'NOVA',
        'NRJ FRANCIA',
        'NUEVATEL',
        'NUR TELECOM',
        'O2',
        'OASIS',
        'OI',
        'OLA - TIGO',
        'OMAN MOBILE',
        'OMNITEL',
        'ONATEL',
        'ONE DOO SKOPJE ',
        'OOREDOO',
        'OOREDOO MYANMAR',
        'OPT - NC MOBILIS',
        'OPTIMUS',
        'OPTUS',
        'ORANGE',
        'ORANGE ',
        'ORANGE F',
        'ORANGE GQ',
        'ORANGE PTY LIMITED VISTA',
        'ORANGE REUNION',
        'ORASCOM',
        'OTT- ORASCOM TUNISIANA',
        'OUTREMER',
        'P&T LUXEMBUR',
        'P4',
        'PAKTEL',
        'PELEPHONE',
        'PERSONAL',
        'PLUS COMMUNICATION',
        'POLKOMTEL',
        'POLSAT',
        'POWERCOM LEO TM',
        'PRIMETEL',
        'PROXIMUS',
        'Q-TELECOM',
        'QATAR TELECOM',
        'QCELL',
        'RADIOMOBIL T-MOBILE',
        'RCS&RDS',
        'RELIANCE TELECOM LTD (MP)',
        'RITABELL - TELE2.MOBIIL',
        'ROBI AXIATA',
        'ROGERS WIRELESS',
        'ROSTELECOM',
        'RS - M:TEL MOBI\'S',
        'SABAFON ',
        'SAFARICOM',
        'SASKATCHEWAN TELECOMMUNICATIONS',
        'SAUDI TELECOM AL JAWAL',
        'SCANCOM',
        'SENTEL',
        'SETAR GSM',
        'SFR',
        'SI.MOBIL',
        'SIMINN',
        'SINGTEL SINGTEL-MOBILELINK',
        'SK TELECOM',
        'SKY MOBILE BEELINE ',
        'SMART',
        'SMARTONE',
        'SMARTS',
        'SOFTBANK MOBILE',
        'SONOFON',
        'SPACETEL',
        'SPACETEL BENIN',
        'SPICE NEPAL SNPL',
        'SPRINT PCS',
        'STARHUB',
        'SUDATEL',
        'SUNRISE',
        'SWISSCOM',
        'SYRIATEL',
        'T +',
        'T-MOBILE',
        'T-MOBILE NL',
        'T-MOBILE UK',
        'T2',
        'TACOM',
        'TAIWAN MOBILE',
        'TANGO',
        'TATA DOCOMO (ANDHARA PRADESH)',
        'TATA DOCOMO (BIHAR)',
        'TATA DOCOMO (DELHI)',
        'TATA DOCOMO (GUJARAT)',
        'TATA DOCOMO (HIMCHAD PRADESH)',
        'TATA DOCOMO (HRYANA)',
        'TATA DOCOMO (KARNATAKA)',
        'TATA DOCOMO (KERALA)',
        'TATA DOCOMO (KOLKOTA)',
        'TATA DOCOMO (MADHYA)',
        'TATA DOCOMO (MAHARASHTRA)',
        'TATA DOCOMO (MUMBAI)',
        'TATA DOCOMO (ORISSA)',
        'TATA DOCOMO (PUNJAB)',
        'TATA DOCOMO (RAJASTHAN)',
        'TATA DOCOMO (RO WB)',
        'TATA DOCOMO (TAMILNADU)',
        'TATA DOCOMO (UP WEST)',
        'TATA DOCOMO (UTTAR PRADESH-EAST)',
        'TCC',
        'TDC MOBIL',
        'TDC NORWAY',
        'TDCA',
        'TELCEL',
        'TELCELL',
        'TELE GREENLAND',
        'TELE2',
        'TELE2 RUSIA',
        'TELECEL',
        'TELECOM',
        'TELECOM ',
        'TELECOMUNICATION',
        'TELEFONICA',
        'TELEFONICA DE NICARAGUA',
        'TELEFONICA GUATEMALA',
        'TELEFONICA MOVILES',
        'TELEFONICA PANAMA',
        'TELEKOM',
        'TELEKOM SL - MOBITEL',
        'TELEKOM SRBIJE',
        'TELEMOVIL - TIGO',
        'TELENOR',
        'TELENOR MYANMAR',
        'TELENOR PANNON',
        'TELESUR',
        'TELFORT',
        'TELIA',
        'TELIA DK',
        'TELIA SONERA',
        'TELIASONERA',
        'TELKOM',
        'TELKOMSEL',
        'TELMA MOBILE',
        'TELSTRA TELECOM',
        'TELUS',
        'THURAYA SATELLITE',
        'TIGO RUANDA',
        'TIM',
        'TIM (CENTRO SUL)',
        'TIM (RIO NORTE)',
        'TIMOR TELECOM',
        'TMN',
        'TNM',
        'TOGOCEL',
        'TRILOGY',
        'TRIMOB',
        'TRUE MOVE - REAL FUTURE',
        'TUNTEL',
        'TURKCELL',
        'TUSMOBIL',
        'TWO DEGREES',
        'U-MOBILE',
        'UFONE',
        'UGANDA TELECOM MOBILE',
        'UMNIAH',
        'UNINOR (ANDHRA PRADESH)',
        'UNINOR (ASSAM)',
        'UNION TELEPHONE',
        'UNITEL',
        'UNKNOWN',
        'UTS',
        'VEGL VODAFONE (GUJARAT)',
        'VEL VODAFONE (MUMBAI)',
        'VERIZON WIRELESS',
        'VIAERO WIRELESS',
        'VIBO',
        'VIDEOTRON',
        'VIETNAMOBILE',
        'VIETTEL MOBILE',
        'VIMPELCOM',
        'VINAPHONE',
        'VINI',
        'VIP',
        'VIP OPERATOR',
        'VIPNET',
        'VIRGIN',
        'VITELCOM',
        'VIVA BAHRAIN',
        'VIVACELL',
        'VIVO',
        'VIVO BRATC',
        'VODACOM',
        'VODAFONE',
        'VOX',
        'VTR',
        'WANA',
        'WARID',
        'WATANIY',
        'WATANIYA',
        'WIND',
        'WIND HELLAS',
        'XFERA',
        'XL AXIATA',
        'YENISEYTELECOM',
        'ZAIN',
        'ZAIN ARABIA',
        'ZAIN IQ',
        'ZANTEL',
    ],
    countryCodes:[
        'AF',
        'AL',
        'DZ',
        'AD',
        'AO',
        'AI',
        'AG',
        'AR',
        'AM',
        'AW',
        'AU',
        'AT',
        'AZ',
        'BS',
        'BH',
        'BD',
        'BB',
        'BY',
        'BE',
        'BZ',
        'BJ',
        'BM',
        'BO',
        'BA',
        'BW',
        'BR',
        'VG',
        'BN',
        'BG',
        'BF',
        'BI',
        'KH',
        'CM',
        'CA',
        'CV',
        'KY',
        'CF',
        'TD',
        'CL',
        'CN',
        'CO',
        'CG',
        'CK',
        'CR',
        'CI',
        'HR',
        'CU',
        'CY',
        'CZ',
        'CD',
        'DK',
        'DJ',
        'DM',
        'DO',
        'EC',
        'EG',
        'SV',
        'EMPTY',
        'GQ',
        'EE',
        'ET',
        'FO',
        'FJ',
        'FI',
        'FR',
        'PF',
        'GA',
        'GM',
        'GE',
        'DE',
        'GH',
        'GI',
        'GR',
        'GL',
        'GD',
        'GP',
        'GU',
        'GT',
        'GW',
        'GN',
        'GY',
        'HT',
        'HN',
        'HK',
        'HU',
        'IS',
        'IN',
        'ID',
        'IR',
        'IQ',
        'IE',
        'IM',
        'IL',
        'IT',
        'JM',
        'JP',
        'JE',
        'JO',
        'KZ',
        'KE',
        'KR',
        'KW',
        'KG',
        'LA',
        'LV',
        'LB',
        'LS',
        'LR',
        'LY',
        'LI',
        'LT',
        'LU',
        'MO',
        'MK',
        'MG',
        'MW',
        'MY',
        'MV',
        'ML',
        'MT',
        'MQ',
        'MR',
        'MU',
        'MX',
        'MD',
        'MC',
        'MN',
        'ME',
        'MS',
        'MA',
        'MZ',
        'MM',
        'NA',
        'NP',
        'AN',
        'NL',
        'NC',
        'NZ',
        'NI',
        'NG',
        'NE',
        'NT',
        'NO',
        'OM',
        'PK',
        'PS',
        'PA',
        'PG',
        'PY',
        'PE',
        'PH',
        'PL',
        'PT',
        'PR',
        'QA',
        'RE',
        'RO',
        'RU',
        'RW',
        'KN',
        'LC',
        'VC',
        'WS',
        'ST',
        'SA',
        'SN',
        'RS',
        'SC',
        'SL',
        'SG',
        'SK',
        'SI',
        'ZA',
        'ES',
        'LK',
        'SD',
        'SR',
        'SE',
        'CH',
        'SY',
        'TW',
        'TJ',
        'TZ',
        'TH',
        'TL',
        'TG',
        'TO',
        'TT',
        'TN',
        'TR',
        'TM',
        'TC',
        'UG',
        'UA',
        'AE',
        'GB',
        'US',
        'VI',
        'UNKNOW',
        'UY',
        'UZ',
        'VU',
        'VE',
        'VN',
        'YE',
        'ZM',
        'ZW',
        'EEUU',
        'USA',
        'UK'
    ],
countryCodesEquivalency:[
        'Afghanistan',
        'Albania (Republic of)',
        'Algeria (People\'s Democratic Republic of)',
        'Andorra (Principality of)',
        'Angola (Republic of)',
        'Anguilla',
        'Antigua and Barbuda',
        'Argentine Republic',
        'Armenia (Republic of)',
        'Aruba',
        'Australia (including Christmas Island and Cocos-Keeling Islands)',
        'Austria',
        'Azerbaijani Republic',
        'Bahamas (Commonwealth of the)',
        'Bahrain (Kingdom of)',
        'Bangladesh (People\'s Republic of)',
        'Barbados',
        'Belarus (Republic of)',
        'Belgium',
        'Belize',
        'Benin (Republic of)',
        'Bermuda',
        'Bolivia (Republic of)',
        'Bosnia and Herzegovina',
        'Botswana (Republic of)',
        'Brazil (Federative Republic of)',
        'British Virgin Islands',
        'Brunei Darussalam',
        'Bulgaria (Republic of)',
        'Burkina Faso',
        'Burundi (Republic of)',
        'Cambodia (Kingdom of)',
        'Cameroon (Republic of)',
        'Canada',
        'Cape Verde (Republic of)',
        'Cayman Islands',
        'Central African Republic',
        'Chad (Republic of)',
        'Chile',
        'China (People\'s Republic of)',
        'Colombia (Republic of)',
        'Congo (Republic of the)',
        'Cook Islands',
        'Costa Rica',
        'Cote d\'Ivoire (Republic of)',
        'Croatia (Republic of)',
        'Cuba',
        'Cyprus (Republic of)',
        'Czech Republic',
        'Democratic Republic of the Congo',
        'Denmark',
        'Djibouti (Republic of)',
        'Dominica (Commonwealth of)',
        'Dominican Republic',
        'Ecuador',
        'Egypt (Arab Republic of)',
        'El Salvador (Republic of)',
        'EMPTY',
        'Equatorial Guinea (Republic of)',
        'Estonia (Republic of)',
        'Ethiopia (Federal Democratic Republic of)',
        'Faroe Islands',
        'Fiji (Republic of)',
        'Finland',
        'France',
        'French Polynesia (Territoire francais d\'outre-mer)',
        'Gabonese Republic',
        'Gambia (Republic of the)',
        'Georgia',
        'Germany (Federal Republic of)',
        'Ghana',
        'Gibraltar',
        'Greece',
        'Greenland (Denmark)',
        'Grenada',
        'Guadeloupe (French Department of)',
        'Guam',
        'Guatemala (Republic of)',
        'Guinea-Bissau (Republic of)',
        'Guinea (Republic of)',
        'Guyana',
        'Haiti (Republic of)',
        'Honduras (Republic of)',
        'Hongkong, China',
        'Hungary (Republic of)',
        'Iceland',
        'India (Republic of)',
        'Indonesia (Republic of)',
        'Iran (Islamic Republic of)',
        'Iraq (Republic of)',
        'Ireland',
        'Isle of Man',
        'Israel (State of)',
        'Italy',
        'Jamaica',
        'Japan',
        'Jersey',
        'Jordan (Hashemite Kingdom of)',
        'Kazakhstan (Republic of)',
        'Kenya (Republic of)',
        'Korea (Republic of)',
        'Kuwait (State of)',
        'Kyrgyz Republic',
        'Lao People\'s Democratic Republic',
        'Latvia (Republic of)',
        'Lebanon',
        'Lesotho (Kingdom of)',
        'Liberia (Republic of)',
        'Libya (Socialist People\'s Libyan Arab Jamahiriya)',
        'Liechtenstein (Principality of)',
        'Lithuania (Republic of)',
        'Luxembourg',
        'Macao, China',
        'Macedonia (The Former Yugoslav Republic of)',
        'Madagascar (Republic of)',
        'Malawi',
        'Malaysia',
        'Maldives (Republic of)',
        'Mali (Republic of)',
        'Malta',
        'Martinique (French Department of)',
        'Mauritania (Islamic Republic of)',
        'Mauritius (Republic of)',
        'Mexico',
        'Moldova (Republic of)',
        'Monaco (Principality of)',
        'Mongolia',
        'Montenegro (Republic of)',
        'Montserrat',
        'Morocco (Kingdom of)',
        'Mozambique (Republic of)',
        'Myanmar (Union of)',
        'Namibia (Republic of)',
        'Nepal',
        'Netherlands Antilles',
        'Netherlands (Kingdom of the)',
        'New Caledonia (Territoire francais d\'outre-mer)',
        'New Zealand',
        'Nicaragua',
        'Nigeria (Federal Republic of)',
        'Niger (Republic of the)',
        'Non Terrestrial (NT)',
        'Norway',
        'Oman (Sultanate of)',
        'Pakistan (Islamic Republic of)',
        'Palestine',
        'Panama (Republic of)',
        'Papua New Guinea',
        'Paraguay (Republic of)',
        'Peru',
        'Philippines (Republic of the)',
        'Poland (Republic of)',
        'Portugal',
        'Puerto Rico',
        'Qatar (State of)',
        'Reunion (French Department of)',
        'Romania',
        'Russian Federation',
        'Rwandese Republic',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Vincent and the Grenadines',
        'Samoa (Independent State of)',
        'Sao Tome and Principe (Democratic Republic of)',
        'Saudi Arabia (Kingdom of)',
        'Senegal (Republic of)',
        'Serbia (Republic of)',
        'Seychelles (Republic of)',
        'Sierra Leone',
        'Singapore (Republic of)',
        'Slovak Republic',
        'Slovenia (Republic of)',
        'South Africa (Republic of)',
        'Spain',
        'Sri Lanka (Democratic Socialist Republic of)',
        'Sudan (Republic of the)',
        'Suriname (Republic of)',
        'Sweden',
        'Switzerland (Confederation of)',
        'Syrian Arab Republic',
        'Taiwan',
        'Tajikistan (Republic of)',
        'Tanzania (United Republic of)',
        'Thailand',
        'Timor-Leste (Democratique Republic of)',
        'Togolese Republic',
        'Tonga (Kingdom of)',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Turks and Caicos Islands',
        'Uganda (Republic of)',
        'Ukraine',
        'United Arab Emirates',
        'United Kingdom of Great Britain and Northern Ireland',
        'United States of America',
        'United States Virgin Islands',
        'UNKNOWN',
        'Uruguay (Eastern Republic of)',
        'Uzbekistan (Republic of)',
        'Vanuatu (Republic of)',
        'Venezuela (Bolivarian Republic of)',
        'Vietnam (Socialist Republic of)',
        'Yemen (Republic of)',
        'Zambia (Republic of)',
        'Zimbabwe (Republic of)',
        'United States of America, USA',
        'United States of America, USA',
        'United Kingdom of Great Britain and Northern Ireland, UK'
    ]
}

var defaultDiacriticsRemovalMap = [
    {'base':'A', 'letters':'\u0041\u24B6\uFF21\u00C0\u00C1\u00C2\u1EA6\u1EA4\u1EAA\u1EA8\u00C3\u0100\u0102\u1EB0\u1EAE\u1EB4\u1EB2\u0226\u01E0\u00C4\u01DE\u1EA2\u00C5\u01FA\u01CD\u0200\u0202\u1EA0\u1EAC\u1EB6\u1E00\u0104\u023A\u2C6F'},
    {'base':'AA','letters':'\uA732'},
    {'base':'AE','letters':'\u00C6\u01FC\u01E2'},
    {'base':'AO','letters':'\uA734'},
    {'base':'AU','letters':'\uA736'},
    {'base':'AV','letters':'\uA738\uA73A'},
    {'base':'AY','letters':'\uA73C'},
    {'base':'B', 'letters':'\u0042\u24B7\uFF22\u1E02\u1E04\u1E06\u0243\u0182\u0181'},
    {'base':'C', 'letters':'\u0043\u24B8\uFF23\u0106\u0108\u010A\u010C\u00C7\u1E08\u0187\u023B\uA73E'},
    {'base':'D', 'letters':'\u0044\u24B9\uFF24\u1E0A\u010E\u1E0C\u1E10\u1E12\u1E0E\u0110\u018B\u018A\u0189\uA779'},
    {'base':'DZ','letters':'\u01F1\u01C4'},
    {'base':'Dz','letters':'\u01F2\u01C5'},
    {'base':'E', 'letters':'\u0045\u24BA\uFF25\u00C8\u00C9\u00CA\u1EC0\u1EBE\u1EC4\u1EC2\u1EBC\u0112\u1E14\u1E16\u0114\u0116\u00CB\u1EBA\u011A\u0204\u0206\u1EB8\u1EC6\u0228\u1E1C\u0118\u1E18\u1E1A\u0190\u018E'},
    {'base':'F', 'letters':'\u0046\u24BB\uFF26\u1E1E\u0191\uA77B'},
    {'base':'G', 'letters':'\u0047\u24BC\uFF27\u01F4\u011C\u1E20\u011E\u0120\u01E6\u0122\u01E4\u0193\uA7A0\uA77D\uA77E'},
    {'base':'H', 'letters':'\u0048\u24BD\uFF28\u0124\u1E22\u1E26\u021E\u1E24\u1E28\u1E2A\u0126\u2C67\u2C75\uA78D'},
    {'base':'I', 'letters':'\u0049\u24BE\uFF29\u00CC\u00CD\u00CE\u0128\u012A\u012C\u0130\u00CF\u1E2E\u1EC8\u01CF\u0208\u020A\u1ECA\u012E\u1E2C\u0197'},
    {'base':'J', 'letters':'\u004A\u24BF\uFF2A\u0134\u0248'},
    {'base':'K', 'letters':'\u004B\u24C0\uFF2B\u1E30\u01E8\u1E32\u0136\u1E34\u0198\u2C69\uA740\uA742\uA744\uA7A2'},
    {'base':'L', 'letters':'\u004C\u24C1\uFF2C\u013F\u0139\u013D\u1E36\u1E38\u013B\u1E3C\u1E3A\u0141\u023D\u2C62\u2C60\uA748\uA746\uA780'},
    {'base':'LJ','letters':'\u01C7'},
    {'base':'Lj','letters':'\u01C8'},
    {'base':'M', 'letters':'\u004D\u24C2\uFF2D\u1E3E\u1E40\u1E42\u2C6E\u019C'},
    {'base':'N', 'letters':'\u004E\u24C3\uFF2E\u01F8\u0143\u00D1\u1E44\u0147\u1E46\u0145\u1E4A\u1E48\u0220\u019D\uA790\uA7A4'},
    {'base':'NJ','letters':'\u01CA'},
    {'base':'Nj','letters':'\u01CB'},
    {'base':'O', 'letters':'\u004F\u24C4\uFF2F\u00D2\u00D3\u00D4\u1ED2\u1ED0\u1ED6\u1ED4\u00D5\u1E4C\u022C\u1E4E\u014C\u1E50\u1E52\u014E\u022E\u0230\u00D6\u022A\u1ECE\u0150\u01D1\u020C\u020E\u01A0\u1EDC\u1EDA\u1EE0\u1EDE\u1EE2\u1ECC\u1ED8\u01EA\u01EC\u00D8\u01FE\u0186\u019F\uA74A\uA74C'},
    {'base':'OI','letters':'\u01A2'},
    {'base':'OO','letters':'\uA74E'},
    {'base':'OU','letters':'\u0222'},
    {'base':'OE','letters':'\u008C\u0152'},
    {'base':'oe','letters':'\u009C\u0153'},
    {'base':'P', 'letters':'\u0050\u24C5\uFF30\u1E54\u1E56\u01A4\u2C63\uA750\uA752\uA754'},
    {'base':'Q', 'letters':'\u0051\u24C6\uFF31\uA756\uA758\u024A'},
    {'base':'R', 'letters':'\u0052\u24C7\uFF32\u0154\u1E58\u0158\u0210\u0212\u1E5A\u1E5C\u0156\u1E5E\u024C\u2C64\uA75A\uA7A6\uA782'},
    {'base':'S', 'letters':'\u0053\u24C8\uFF33\u1E9E\u015A\u1E64\u015C\u1E60\u0160\u1E66\u1E62\u1E68\u0218\u015E\u2C7E\uA7A8\uA784'},
    {'base':'T', 'letters':'\u0054\u24C9\uFF34\u1E6A\u0164\u1E6C\u021A\u0162\u1E70\u1E6E\u0166\u01AC\u01AE\u023E\uA786'},
    {'base':'TZ','letters':'\uA728'},
    {'base':'U', 'letters':'\u0055\u24CA\uFF35\u00D9\u00DA\u00DB\u0168\u1E78\u016A\u1E7A\u016C\u00DC\u01DB\u01D7\u01D5\u01D9\u1EE6\u016E\u0170\u01D3\u0214\u0216\u01AF\u1EEA\u1EE8\u1EEE\u1EEC\u1EF0\u1EE4\u1E72\u0172\u1E76\u1E74\u0244'},
    {'base':'V', 'letters':'\u0056\u24CB\uFF36\u1E7C\u1E7E\u01B2\uA75E\u0245'},
    {'base':'VY','letters':'\uA760'},
    {'base':'W', 'letters':'\u0057\u24CC\uFF37\u1E80\u1E82\u0174\u1E86\u1E84\u1E88\u2C72'},
    {'base':'X', 'letters':'\u0058\u24CD\uFF38\u1E8A\u1E8C'},
    {'base':'Y', 'letters':'\u0059\u24CE\uFF39\u1EF2\u00DD\u0176\u1EF8\u0232\u1E8E\u0178\u1EF6\u1EF4\u01B3\u024E\u1EFE'},
    {'base':'Z', 'letters':'\u005A\u24CF\uFF3A\u0179\u1E90\u017B\u017D\u1E92\u1E94\u01B5\u0224\u2C7F\u2C6B\uA762'},
    {'base':'a', 'letters':'\u0061\u24D0\uFF41\u1E9A\u00E0\u00E1\u00E2\u1EA7\u1EA5\u1EAB\u1EA9\u00E3\u0101\u0103\u1EB1\u1EAF\u1EB5\u1EB3\u0227\u01E1\u00E4\u01DF\u1EA3\u00E5\u01FB\u01CE\u0201\u0203\u1EA1\u1EAD\u1EB7\u1E01\u0105\u2C65\u0250'},
    {'base':'aa','letters':'\uA733'},
    {'base':'ae','letters':'\u00E6\u01FD\u01E3'},
    {'base':'ao','letters':'\uA735'},
    {'base':'au','letters':'\uA737'},
    {'base':'av','letters':'\uA739\uA73B'},
    {'base':'ay','letters':'\uA73D'},
    {'base':'b', 'letters':'\u0062\u24D1\uFF42\u1E03\u1E05\u1E07\u0180\u0183\u0253'},
    {'base':'c', 'letters':'\u0063\u24D2\uFF43\u0107\u0109\u010B\u010D\u00E7\u1E09\u0188\u023C\uA73F\u2184'},
    {'base':'d', 'letters':'\u0064\u24D3\uFF44\u1E0B\u010F\u1E0D\u1E11\u1E13\u1E0F\u0111\u018C\u0256\u0257\uA77A'},
    {'base':'dz','letters':'\u01F3\u01C6'},
    {'base':'e', 'letters':'\u0065\u24D4\uFF45\u00E8\u00E9\u00EA\u1EC1\u1EBF\u1EC5\u1EC3\u1EBD\u0113\u1E15\u1E17\u0115\u0117\u00EB\u1EBB\u011B\u0205\u0207\u1EB9\u1EC7\u0229\u1E1D\u0119\u1E19\u1E1B\u0247\u025B\u01DD'},
    {'base':'f', 'letters':'\u0066\u24D5\uFF46\u1E1F\u0192\uA77C'},
    {'base':'g', 'letters':'\u0067\u24D6\uFF47\u01F5\u011D\u1E21\u011F\u0121\u01E7\u0123\u01E5\u0260\uA7A1\u1D79\uA77F'},
    {'base':'h', 'letters':'\u0068\u24D7\uFF48\u0125\u1E23\u1E27\u021F\u1E25\u1E29\u1E2B\u1E96\u0127\u2C68\u2C76\u0265'},
    {'base':'hv','letters':'\u0195'},
    {'base':'i', 'letters':'\u0069\u24D8\uFF49\u00EC\u00ED\u00EE\u0129\u012B\u012D\u00EF\u1E2F\u1EC9\u01D0\u0209\u020B\u1ECB\u012F\u1E2D\u0268\u0131'},
    {'base':'j', 'letters':'\u006A\u24D9\uFF4A\u0135\u01F0\u0249'},
    {'base':'k', 'letters':'\u006B\u24DA\uFF4B\u1E31\u01E9\u1E33\u0137\u1E35\u0199\u2C6A\uA741\uA743\uA745\uA7A3'},
    {'base':'l', 'letters':'\u006C\u24DB\uFF4C\u0140\u013A\u013E\u1E37\u1E39\u013C\u1E3D\u1E3B\u017F\u0142\u019A\u026B\u2C61\uA749\uA781\uA747'},
    {'base':'lj','letters':'\u01C9'},
    {'base':'m', 'letters':'\u006D\u24DC\uFF4D\u1E3F\u1E41\u1E43\u0271\u026F'},
    {'base':'n', 'letters':'\u006E\u24DD\uFF4E\u01F9\u0144\u00F1\u1E45\u0148\u1E47\u0146\u1E4B\u1E49\u019E\u0272\u0149\uA791\uA7A5'},
    {'base':'nj','letters':'\u01CC'},
    {'base':'o', 'letters':'\u006F\u24DE\uFF4F\u00F2\u00F3\u00F4\u1ED3\u1ED1\u1ED7\u1ED5\u00F5\u1E4D\u022D\u1E4F\u014D\u1E51\u1E53\u014F\u022F\u0231\u00F6\u022B\u1ECF\u0151\u01D2\u020D\u020F\u01A1\u1EDD\u1EDB\u1EE1\u1EDF\u1EE3\u1ECD\u1ED9\u01EB\u01ED\u00F8\u01FF\u0254\uA74B\uA74D\u0275'},
    {'base':'oi','letters':'\u01A3'},
    {'base':'ou','letters':'\u0223'},
    {'base':'oo','letters':'\uA74F'},
    {'base':'p','letters':'\u0070\u24DF\uFF50\u1E55\u1E57\u01A5\u1D7D\uA751\uA753\uA755'},
    {'base':'q','letters':'\u0071\u24E0\uFF51\u024B\uA757\uA759'},
    {'base':'r','letters':'\u0072\u24E1\uFF52\u0155\u1E59\u0159\u0211\u0213\u1E5B\u1E5D\u0157\u1E5F\u024D\u027D\uA75B\uA7A7\uA783'},
    {'base':'s','letters':'\u0073\u24E2\uFF53\u00DF\u015B\u1E65\u015D\u1E61\u0161\u1E67\u1E63\u1E69\u0219\u015F\u023F\uA7A9\uA785\u1E9B'},
    {'base':'t','letters':'\u0074\u24E3\uFF54\u1E6B\u1E97\u0165\u1E6D\u021B\u0163\u1E71\u1E6F\u0167\u01AD\u0288\u2C66\uA787'},
    {'base':'tz','letters':'\uA729'},
    {'base':'u','letters': '\u0075\u24E4\uFF55\u00F9\u00FA\u00FB\u0169\u1E79\u016B\u1E7B\u016D\u00FC\u01DC\u01D8\u01D6\u01DA\u1EE7\u016F\u0171\u01D4\u0215\u0217\u01B0\u1EEB\u1EE9\u1EEF\u1EED\u1EF1\u1EE5\u1E73\u0173\u1E77\u1E75\u0289'},
    {'base':'v','letters':'\u0076\u24E5\uFF56\u1E7D\u1E7F\u028B\uA75F\u028C'},
    {'base':'vy','letters':'\uA761'},
    {'base':'w','letters':'\u0077\u24E6\uFF57\u1E81\u1E83\u0175\u1E87\u1E85\u1E98\u1E89\u2C73'},
    {'base':'x','letters':'\u0078\u24E7\uFF58\u1E8B\u1E8D'},
    {'base':'y','letters':'\u0079\u24E8\uFF59\u1EF3\u00FD\u0177\u1EF9\u0233\u1E8F\u00FF\u1EF7\u1E99\u1EF5\u01B4\u024F\u1EFF'},
    {'base':'z','letters':'\u007A\u24E9\uFF5A\u017A\u1E91\u017C\u017E\u1E93\u1E95\u01B6\u0225\u0240\u2C6C\uA763'}
];

var diacriticsMap = {};
for (var i=0; i < defaultDiacriticsRemovalMap .length; i++){
    var letters = defaultDiacriticsRemovalMap [i].letters;
    for (var j=0; j < letters.length ; j++){
        diacriticsMap[letters[j]] = defaultDiacriticsRemovalMap [i].base;
    }
}

function removeDiacritics (str) {
    return str.replace(/[^\u0000-\u007E]/g, function(a){ 
       return diacriticsMap[a] || a; 
    });
} 

function removeStopWords(str){
    for(var i=0; i<stopWordsSpanish.length;i++){
        str.replaceAll(stopWordsSpanish[i]+ " ");
        str.replaceAll(" "+stopWordsSpanish[i]);
    }
    return str;
}

var stopWordsSpanish = [
  'a',
  'un',
  'una',
  'unas',
  'unos',
  'uno',
  'sobre',
  'de',
  'todo',
  'también',
  'tras',
  'otro',
  'algún',
  'alguno',
  'alguna',
  'algunos',
  'algunas',
  'ser',
  'es',
  'soy',
  'eres',
  'somos',
  'sois',
  'esto',
  'estoy',
  'esta',
  'estamos',
  'estais',
  'estan',
  'como',
  'en',
  'para',
  'atras',
  'porque',
  'por qué',
  'estado',
  'estaba',
  'ante',
  'antes',
  'siendo',
  'ambos',
  'pero',
  'por',
  'no',
  'poder',
  'sal',
  'al',
  'puede',
  'puedo',
  'más',
  'ya',
  'le',
  'o',
  'me',
  'hasta',
  'durante',
  'ni',
  'ese',
  'contra',
  'eso',
  'mí',
  'mi',
  'el',
  'él',
  'podemos',
  'podeis',
  'pueden',
  'fui',
  'fue',
  'fuimos',
  'fueron',
  'hacer',
  'hago',
  'hace',
  'hacemos',
  'haceis',
  'hacen',
  'cada',
  'fin',
  'incluso',
  'primero',
  'desde',
  'conseguir',
  'consigo',
  'consigue',
  'consigues',
  'conseguimos',
  'consiguen',
  'ir',
  'voy',
  'va',
  'vamos',
  'vais',
  'van',
  'vaya',
  'gueno',
  'ha',
  'tener',
  'tengo',
  'tiene',
  'tenemos',
  'teneis',
  'tienen',
  'la',
  'lo',
  'las',
  'los',
  'su',
  'aqui',
  'mio',
  'poco',
  'tu',
  'tú',
  'te',
  'si',
  'sí',
  'tuyo',
  'ellos',
  'ella',
  'y',
  'del',
  'se',
  'ellas',
  'nos',
  'nosotros',
  'vosotros',
  'vosotras',
  'si',
  'dentro',
  'solo',
  'solamente',
  'saber',
  'sabes',
  'sabe',
  'sabemos',
  'sabeis',
  'saben',
  'ultimo',
  'largo',
  'bastante',
  'haces',
  'muchos',
  'aquellos',
  'aquellas',
  'sus',
  'entonces',
  'tiempo',
  'verdad',
  'verdadero',
  'verdadera',
  'cierto',
  'ciertos',
  'cierta',
  'ciertas',
  'intentar',
  'intento',
  'intenta',
  'intentas',
  'intentamos',
  'intentais',
  'intentan',
  'dos',
  'bajo',
  'arriba',
  'encima',
  'usar',
  'uso',
  'usas',
  'usa',
  'usamos',
  'usais',
  'usan',
  'emplear',
  'empleo',
  'empleas',
  'emplean',
  'ampleamos',
  'empleais',
  'valor',
  'muy',
  'era',
  'eras',
  'eramos',
  'eran',
  'modo',
  'bien',
  'cual',
  'cuando',
  'donde',
  'mientras',
  'quien',
  'con',
  'entre',
  'sin',
  'trabajo',
  'trabajar',
  'trabajas',
  'trabaja',
  'trabajamos',
  'trabajais',
  'trabajan',
  'podria',
  'podrias',
  'podriamos',
  'podrian',
  'podriais',
  'yo',
  'aquel',
  'que',
  '1','2','3','4','5','6','7','8','9','0'
]

/*
* Replace all occurrences for a string
* @param {string} search
* @param {string} replacement
*/
String.prototype.replaceAll = function(search, replacement) {
    var target = this;
    return target.replace(new RegExp(search, 'g'), replacement);
};